name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -qq nasm g++-multilib gcc-multilib libc6-dev-i386 python3-pip python3-setuptools
      - run: sudo python3 -m pip install meson==0.52.1 ninja
      - run: more /proc/cpuinfo
      - run: nasm -v
      - run: c++ --version
      - run: gcc -Q --help=target
      - run: make gmp-bootstrap
      - run: make gtest-bootstrap
      - run: meson builddir --werror
      - run: ninja -C builddir -v
      - run: ( cd test/encoder_binary_comparison ; CFLAGS=-Werror ./run_PrepareAllTestData.sh 64 )
      - run: meson test -C builddir -v
      # - run: ./run_Test.sh BinaryCompare BA_MW_D.264
      # - run: ./run_Test.sh BinaryCompare Adobe_PDF_sample_a_1024x768_50Frms.264
      # - run: ./run_Test.sh BinaryCompare Zhling_1280x720.264
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: .
